version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:9.6
    env_file: dev-env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - weather-service-network

  weather-api:
    container_name: weather-api
    build: .
    env_file: dev-env
    command: ["sh", "scripts/start.sh"]
    ports:
      - 4000:4000
    volumes:
      - .:/weather-service
    depends_on:
      - db
    networks:
      - weather-service-network

volumes:
  pg-data: {}

networks:
  weather-service-network:
    name: weather-service-network
    driver: bridge